### ISSUE TITLE
NO wave tables

### ISSUE THREAD

**Issue by pirvcb** [scraptured/ModularArduinoV2#1]
Hi there!
I liked so much your Arduino Synth works!
I tried out without originals (yours) wave tables, and are brilliant.
Could you ppublish them?
TIA
Davide

**Comment by scraptured** [comment]
Hi Davide,
I'm glad that you like them! I've uploaded a bunch of custom wavetables in a new repository called "CustomMozziWavetables". In that repository you will also find two python scripts that I used to make all the wavetable header files. 

I hope you find them useful and good luck on your projects!

Daniel

**Comment by pirvcb** [comment]
Thank you very very much, Daniel!

Davide

**Comment by pirvcb** [comment]
Hello Daniel. Sorry to bother you again but also Drone Synth Wavetables are not here.
Could you kindly up them also?
Thanks again!

**Comment by scraptured** [comment]
Unfortunately I can't; those wavetables got deleted. Just replaced them with different ones in the code. =)
